"""initial migration

Revision ID: 2db38093214c
Revises: 5ed48b1fd30a
Create Date: 2026-06-29 14:00:12.055297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db38093214c'
down_revision: Union[str, Sequence[str], None] = '5ed48b1fd30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_phone_key'), 'companies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('companies_phone_key'), 'companies', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
